### ISSUE TITLE
DeprecatedAnalyzer throws a NullReferenceException

### ISSUE THREAD

**Issue by CoolDadTx** [dotnet/platform-compat#101]
In my .NET 4.6.1 class library I have some code marked as obsolete. The analyze throws a NullReferenceException when build code. The code it gives is AD0001. Seems to throw it once per project that has such an attribute.

**Comment by svick** [comment]
I can't reproduce this. Can you share code that causes this exception and also the stack trace of the exception?

**Comment by CoolDadTx** [comment]
The solution I'm compiling is located [here](https://github.com/CoolDadTx/kraken).

**Comment by pjanotti** [comment]
@CoolDadTx I tried the project and I hit the same as #96: a special case when the property is set but it doesn't have a set method, the compiler goes straight to the backfield. I will leave this one open until we publish a release with the fix. If you want to capture the stacks for this case and locate the exact sources causing the exception, see https://github.com/dotnet/platform-compat/issues/97#issuecomment-370666016

**Comment by CoolDadTx** [comment]
It is line 26 in the DataCommand.cs constructor. It is setting CommandText. That property has a public getter and private setter. Sounds like the same issue.

`
public class DataCommand
{
   public DataCommand ( string commandText, CommandType type )
   {
      CommandText = commandText;
   }

   public string CommandText { get; private set; }
}
`

**Comment by pjanotti** [comment]
@CoolDadTx version 0.2.12-alpha was released earlier today. Let's know if you still have any problems with it.

**Comment by CoolDadTx** [comment]
The latest version fixes the issue for me.
