### ISSUE TITLE
How to ignore PC003 for specific platform?

### ISSUE THREAD

**Issue by Krakean** [dotnet/platform-compat#107]
@jmarolf @terrajobst  @pjanotti 
I have this string in my Directory.Build.props (using .NET Core 2.0):
...
    <PlatformCompatIgnore>UWP</PlatformCompatIgnore> 
...

But it seems like doesn't work:
1>3rdParty\NativeLibraryLoader\Source\Libdl.cs(13,37,13,43): warning PC003: libdl!dlopen isn't available in UWP
1>3rdParty\NativeLibraryLoader\Source\Libdl.cs(16,37,16,42): warning PC003: libdl!dlsym isn't available in UWP
1>3rdParty\NativeLibraryLoader\Source\Libdl.cs(19,34,19,41): warning PC003: libdl!dlclose isn't available in UWP
1>3rdParty\NativeLibraryLoader\Source\Libdl.cs(22,37,22,44): warning PC003: libdl!dlerror isn't available in UWP

So, question: how to properly disable PC003 for specific platform that I dont care?

**Comment by Krakean** [comment]
@jmarolf @terrajobst @pjanotti bump?

**Comment by jmarolf** [comment]
`PC003` is only for UWP.  If you are not targeting that platform at all then I would disable `PC003` for your project.

**Comment by Krakean** [comment]
@jmarolf I ignore whole platform via Directory.Build.props:
https://i.imgur.com/z2j6Qly.png

But it doesn't work.

**Comment by jmarolf** [comment]
As per the [docs](https://github.com/dotnet/platform-compat/blob/master/docs/PC001.md): `UWP` isn't a string that `PC001` understands, it only knows about `Linux`, `macOS`, and `Windows`.  This is fine as `PC001` does not produce any diagnostics about UWP apps.

`PC003` reports errors regarding UWP and can be disabled by
1. Expanding the analyzers node on your project
![image](https://user-images.githubusercontent.com/9797472/38752718-1d39b8de-3f11-11e8-9d9e-361e4e104f77.png)
2. Right-clicking and setting the rule severity to '`None`'
![image](https://user-images.githubusercontent.com/9797472/38752768-38b30a8e-3f11-11e8-9284-576153ea189b.png)

This will create a ruleset file that looks something like this:
```XML
<?xml version="1.0" encoding="utf-8"?>
<RuleSet Name="My Rules" Description="." ToolsVersion="10.0">
  <Rules AnalyzerId="Microsoft.DotNet.Analyzers.Compatibility"
         RuleNamespace="Microsoft.DotNet.Analyzers.Compatibility">
    <Rule Id="PC003" Action="None" />
  </Rules>
</RuleSet>
```
You can then include this ruleset file in any project where you want this rule disabled
```XML
  <PropertyGroup>
    <CodeAnalysisRuleSet>MyRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
```

**Comment by Krakean** [comment]
Thanks. Solved.
