### ISSUE TITLE
Delegate.BeginInvoke/EndInvoke not supported on any OS

### ISSUE THREAD

**Issue by jnm2** [dotnet/platform-compat#129]
Re: https://github.com/dotnet/winforms/issues/242#issuecomment-447650199

> > The `BeginInvoke` call is something I think https://docs.microsoft.com/dotnet/standard/analyzers/api-analyzer would have caught at compile time, IIRC.
> 
> I gave it a try, to my surprise `Delegate.BeginInvoke` is not detected by the analyzer.

**Comment by mjrousos** [comment]
I'm working on a PR to add support for this. I don't have the ability to assign issues, but @terrajobst, feel free to assign this to me.
