### ISSUE TITLE
Allow deprecation information to be pulled from remote sources

### ISSUE THREAD

**Issue by filipw** [dotnet/platform-compat#27]
At the moment the deprecation data is embedded into the analyzer. 

This means that:
 - new deprecations require update of the package
 - I cannot add my own custom deprecations

It would be nice if the analyzer allowed me to configure sources where it looks for deprecations (ideally over the network), rather than just loading the embedded data.

**Comment by OliaG** [comment]
The second one is a duplicate to #9 .

**Comment by OliaG** [comment]
The first one is by design.
