### ISSUE TITLE
Consider also offering as a VS extension

### ISSUE THREAD

**Issue by bording** [dotnet/platform-compat#28]
Any plans to also offer this as a VS extension? That would allow for any project to be analyzed without having to add a NuGet package to it first.

**Comment by terrajobst** [comment]
I'm not opposed to that, especially because I already have the VSIX project for debugging anyways.

My question would be: how useful would this be in practice considering that the only way you get the warnings on build servers is by adding the NuGet package. The VSIX would only give you warnings in that particular VS installation.

**Comment by bording** [comment]
I think both scenarios have value.  Having the extension mean you can analyze any project you open locally without first having to think about modifying the project. Then, if it makes sense to have this continually checked on an ongoing basis, you can decide to install the NuGet package and get build server warning.

**Comment by jnm2** [comment]
A VSIX to suggest that you add the NuGet package 😈

**Comment by terrajobst** [comment]
We're also considering to eventually add this tool to the SDK so that the analyzer runs by default. This would achieve the same thing.

**Comment by terrajobst** [comment]
Actually, it's currently not technically feasible to provide a VISX. As [I've written here](https://blogs.msdn.microsoft.com/dotnet/2017/10/31/introducing-api-analyzer/#comment-399006):

> To add to what Olia said: the primary reason was so that we can gather feedback today and have an easy way to ship updates to collect feedback. Requiring an SDK update/VS update makes it significantly harder to get people to use on their real world projects right away.
>
> We could have made it a VSIX but that has two problems: they don’t participate in command line builds, they don’t travel to the CI system, **and the analyzer wouldn’t be able to get access to the build environment** (target framework) without making it a system wide install (MSI).
