### ISSUE TITLE
False positive for Activator.CreateInstance

### ISSUE THREAD

**Issue by bording** [dotnet/platform-compat#32]
I'm seeing the following warning:
```
PC001 Activator.CreateInstance(Type, params object[]) isn't supported on Linux, MacOSX, Windows	
```
But when testing this out with the following code, it works correctly on all platforms without throwing an exception:

```csharp
using System;

namespace TestPlatform
{
    class Program
    {
        static void Main(string[] args)
        {
            var instance = Activator.CreateInstance(typeof(Test), 100, "42");
        }
    }

    class Test
    {
        int first;
        string second;

        public Test(int one, string two)
        {
            first = one;
            second = two;
        }
    }
}
```

**Comment by elevate-andrewlock** [comment]
I'm getting similar false positives with `Activator.CreateInstance`.

I'm also getting a false positive with `AutoResetEvent evnt = new AutoResetEvent(false)`. Seeing as `AutoResetEvent` is used in [dotnet/corefx](https://github.com/dotnet/corefx/blob/1d9e682f81bf5c7775f223e8f5bf8cd526bc1b54/src/System.Threading/tests/AutoResetEventTests.cs), and is listed in the [.NET Core 2.0 API browser](https://docs.microsoft.com/en-gb/dotnet/api/system.threading.autoresetevent?view=netcore-2.0) I assume this is a false positive too?

Same goes for `HMACSHA1` - generates PC001 warning, but listed in .NET Core 2.0 api browser.

**Comment by pjanotti** [comment]
As you saw the automated scan has some false positives I am working on a manually curated list of PNSE exceptions, then some work to track this manual exclusions.

**Comment by pjanotti** [comment]
/cc @bording @elevate-andrewlock 

I am adding the cases of `Activator.CreateInstance` and sync primitives via #35. Some of them are simply incorrect and added to a exclusion list while some of them are being moved to deprecation since it is not possible to use a given parameter, so the recommendation becomes to use alternative overloads.

**Comment by pjanotti** [comment]
@bording Yes, please. It will be very helpful.

**Comment by pjanotti** [comment]
@elevate-andrewlock 
> ... generates PC001 warning, but listed in .NET Core 2.0 api browser.
Those listed in your comment are false-positives but notice that is possible for some method/property to be in .NET Core 2.0 and for it to throw `PlatformNotSupportedException` . This tool is to try to reduce such bad surprises and point the real ones.

**Comment by terrajobst** [comment]
@elevate-andrewlock 

> Personally, I feel like the decision to make `PlatformNotSupportedException`s an acceptable way of "implementing" .NET Standard completely undermines the whole premise of portable, cross-platform code :( 

It's a trade-off. See this [entry in our FAQ](https://github.com/dotnet/standard/blob/master/docs/faq.md#will-there-be-tooling-to-highlight-apis-that-dont-work-everywhere)

**Comment by elevate-andrewlock** [comment]
Yep, totally understand the decision, I guess I just don't necessarily agree with it due to the ambiguity it introduces :) This analyzer should go a long way to fixing that though 👍

**Comment by pjanotti** [comment]
@elevate-andrewlock @bording - the APIs mentioned here were covered in #35, I will close this item but please keep raising issues for any false positives that you may find, I did some scan of that but it is a large surface...
