### ISSUE TITLE
Typo in GitHub release page

### ISSUE THREAD

**Issue by jnm2** [dotnet/platform-compat#36]
Spotted ‘analzyer’ in https://github.com/dotnet/platform-compat/releases/tag/v0.0.95-alpha.

**Comment by terrajobst** [comment]
Good catch. Fixed.

**Comment by jnm2** [comment]
Well, now I'm spotting ‘anayzer’ there. 😄

**Comment by terrajobst** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/5169960/30936485-e565ef46-a388-11e7-8ae9-e503817ec755.png)

**Comment by jnm2** [comment]
:+1: Anyway, you're making me feel less alone in the world with my own typos. 😃
