### ISSUE TITLE
Distinguish between get/set property

### ISSUE THREAD

**Issue by pjanotti** [dotnet/platform-compat#39]
This can be useful to more precise diagnostic messages, need to evaluate if there are downsides (e.g.: size of resource?)

**Comment by terrajobst** [comment]
Agreed. The way I'd do this is record either the setter, the getter, or the property (if both getter and setter are affected).

In the lookup, I'd handle:

* AssignmentExpression to check for the setter and disable walking the target to avoid also looking for the setter/property
* Change the generic handler to also check for the property getter when the symbol is a property

We might want to do the same for events, but I don't think adders/removers will likely have different data.

**Comment by terrajobst** [comment]
FYI: This bug is causing false positives for the demo we've been using for a while, specifically `Console.WindowWidth` and `Console.WindowHeight`. The setter isn't supported, but the getter is.

https://github.com/dotnet/corefx/blob/93764c0991d167e3b74f41f1ea129004ce10598c/src/System.Console/src/System/ConsolePal.Unix.cs#L253-L263

**Comment by pjanotti** [comment]
First pass by simply breaking down get/set gets an increase of ~13KB on the csv loaded as resource. I didn't measure the impact on the DB in memory yet but likely we will be good on this regard.

Regarding the events there is only 1 event was detected by the tool, and as expected it has both add and remove throwing PNSE. At such low cost I am tempted to leave it and deal it in a manner symmetrical to the properties.

**Comment by terrajobst** [comment]
> First pass by simply breaking down get/set gets an increase of ~13KB on the csv loaded as resource. I didn't measure the impact on the DB in memory yet but likely we will be good on this regard.

Is that because of we record the data twice or because the signatures are longer? We can fix the former by continue to recording a single row for property (if both setter and getter throw).

**Comment by pjanotti** [comment]
Mostly *it seems* due to longer signatures: most of the properties are replaced by a single get or set that is a bit longer, few like registry then two lines where before we had just one.
