### ISSUE TITLE
Readme usage link 404s

### ISSUE THREAD

**Issue by jnm2** [dotnet/platform-compat#41]
https://github.com/dotnet/platform-compat#usage:

> In order to use it, install the NuGet package [PlatformCompat.Analyzers](https://www.nuget.org/packages/PlatformCompat.analyzers).

https://www.nuget.org/packages/PlatformCompat.analyzers yields a 404. The current link is https://www.nuget.org/packages/Terrajobst.PlatformCompat.Analyzers.

**Comment by pjanotti** [comment]
Thanks @jnm2.

@terrajobst After PR #35 is done we should publish the package on its newest location.

**Comment by terrajobst** [comment]
Sounds good. Just approved #35, so feel free to merge.
