### ISSUE TITLE
GlobalSuppressions causes DeprecatedAnalyzer to NRE

### ISSUE THREAD

**Issue by jnm2** [dotnet/platform-compat#59]
If I use VS code fix to add AD0001 to the GlobalSuppressions.cs, it causes DeprecatedAnalyzer to NRE.

```cs
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "DE0001:API is deprecated", Justification = "<Pending>", Scope = "type", Target = "~T:Foo")]
```

> AD0001 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

Now since I don't have the granularity to globally suppress a certain deprecated type and not other deprecated types, I'll obviously not be using `GlobalSuppressions.cs`. But I thought I'd report it all the same.

**Comment by jnm2** [comment]
Hang on, testing mistake. It actually NREs on `#pragma warning disable DE0001` as well as `GlobalSuppressions` which makes more sense.

**Comment by springy76** [comment]
I just added this NuGet package to an existing solution containing ~25 projects and 2-3 of them throw this exact same exception AD0001. I did not configure anything yet, just added it.

**Comment by pjanotti** [comment]
What version of VS were you using? If you can provide files/solution with a repro it will be very helpful.

**Comment by marksmeltzer** [comment]
I'm getting this as well. I added the compatibility analyzer freshly to project. Using latest VS 2017 (15.5.7) and the latest analyzer (0.1.3-alpha).

Warning	AD0001	Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

I added some suppressions and code changes thinking that this error might clear afterwards once all deprecated APIs were addresses, but this error persists.

**Comment by pjanotti** [comment]
I can't repro the initial issue described here, but there was a NRE fixed in #96. Perhaps are you hitting that one?

**Comment by pjanotti** [comment]
I thought that it was added to Roslyn sometime ago https://github.com/dotnet/roslyn/pull/1742 but that doesn't seem to show in VS ... anything that you can use to capture the stack will be very helpful. Thanks!

**Comment by pjanotti** [comment]
Hi @marksmeltzer, @springy76,  and  @jnm2 could you please give a try with latest nugget and see if we still have this issue? If yes, the instructions below can be used to get a call stack, they also provide indication of the exact source causing the issue that we can use to code a small repro.

* Add a <ErrorLog> property to the csproj and it will capture stacks for analyzers crashes on next build, e.g.: <ErrorLog>analyzerErrors.json</ErrorLog>
* On VS the AD0001 warnings just capture the callstack if it is triggered by IntelliSense, i.e.: if you are editing the specific file causing the exception (likely hard to find in large projects).

Thanks

**Comment by springy76** [comment]
@pjanotti a quick test using 0.2.12 (without the <ErrorLog>) reduced the count back to 6.

5 of them just disappeared after expanding the error node and I could see for a second that the message details contained already a stacktrace.

The 6th of them then did not disappear:
SyntaxNode: this.viewRoot - this.HeaderSize ... [BinaryExpressionSyntax]@[1996..2027) (57,10)-(57,41)

```
System.NullReferenceException: 
   at Microsoft.DotNet.Analyzers.Compatibility.Store.ApiStore`1.GetKey(ISymbol symbol)
   at Microsoft.DotNet.Analyzers.Compatibility.Store.ApiStore`1.TryLookup(ISymbol symbol, ApiEntry`1& entry)
   at Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer.AnalyzeSymbol(SymbolUsageAnalysisContext context)
   at Microsoft.DotNet.Analyzers.Compatibility.SymbolUsageAnalysisExtensions.Handle(SyntaxNodeAnalysisContext context, ExpressionSyntax node, Action`1 action)
   at Microsoft.DotNet.Analyzers.Compatibility.SymbolUsageAnalysisExtensions.Handle(SyntaxNodeAnalysisContext context, Action`1 action)
   at Microsoft.DotNet.Analyzers.Compatibility.SymbolUsageAnalysisExtensions.<>c__DisplayClass2_0.<RegisterSyntaxNodeAction>b__0(SyntaxNodeAnalysisContext nodeContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__43`1.<ExecuteSyntaxNodeAction>b__43_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
```

**Comment by jnm2** [comment]
@pjanotti Using 0.2.12-alpha I'm no longer seeing this issue.

**Comment by pjanotti** [comment]
Thanks for looking @jnm2 and @springy76.

I have some other higher priority work to do before I can fix this, so it may take a bit to get them fixed.

**Comment by pjanotti** [comment]
@springy76 did you explicit try rebuild after adding the `<ErrorLog>` to your porject? If the json file after a rebuild is still the StyleCop one, could you please open an issue at https://github.com/dotnet/roslyn/issues Thanks

**Comment by pjanotti** [comment]
@springy76 have you tried 0.2.13? I have tried your code above and didn't get a repro so I'm assuming that fixes for other crashes on the analyzer resolved this. Feel free to re-open if you still hit some crash.

**Comment by springy76** [comment]
.13? No, because there is none: (https://www.nuget.org/packages?q=Microsoft.DotNet.Analyzers.Compatibility)

**Comment by pjanotti** [comment]
Ops, mixed the versions... so I must assume that the issue still repros for you, correct? I need to understand the diff between my attempted repro and your code...

**Comment by pjanotti** [comment]
Thanks @springy76.
