### ISSUE TITLE
VSIX Release Version?

### ISSUE THREAD

**Issue by nnpcYvIVl** [dotnet/platform-compat#65]
Would you consider releasing this as a VSIX?

Throughout the day I use Visual Studio to open and manage lots of different projects and adding analyzers to each one is not always possible. It would be nice to have a system-wide version that would work on any project open in my environment.

**Comment by OliaG** [comment]
As discussed [here](https://github.com/dotnet/platform-compat/issues/28#issuecomment-343516187) decided it's technically impossible.
