### ISSUE TITLE
Avoid "OSX" in warning messages?

### ISSUE THREAD

**Issue by justinvp** [dotnet/platform-compat#67]
The use of "MacOSX" in the warnings looks dated.

<img width="590" alt="screen shot 2017-11-17 at 8 36 55 am" src="https://user-images.githubusercontent.com/710598/32958401-37883b3c-cb73-11e7-8a5d-bc8f506b2468.png">

Apple no longer uses "OS X". They call it "macOS" (yes, lowercase 'm', to align with the naming of iOS, watchOS, and tvOS).

Should these warnings use "macOS" or simply "Mac", instead of "MacOSX"?

**Comment by terrajobst** [comment]
Right now, I'm just ToString'ing the internal enum we use. Easy fix though. Would also address #62.
