### ISSUE TITLE
Update the text in NuGet pkg to cover deprecation case as well

### ISSUE THREAD

**Issue by OliaG** [dotnet/platform-compat#89]
Right now our text contains only compatibility scenario.
![api-analyzer-in-nuget](https://user-images.githubusercontent.com/31997351/35019508-20b22d9e-fadc-11e7-9ba2-7173b349dd58.jpg)

**Comment by pjanotti** [comment]
What text we want there? "Shows diagnostics related to deprecation and portability of .NET Core APIs" ?
