### ISSUE TITLE
AD0001 null reference exception

### ISSUE THREAD

**Issue by Krakean** [dotnet/platform-compat#99]
@pjanotti @terrajobst 
Using 0.2.15-alpha:

8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
8>CSC : warning AD0001: Analyzer 'Microsoft.DotNet.Analyzers.Compatibility.Deprecated.DeprecatedAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.

And there is much more of them!
Same with 0.1.3

Any way to provide you additional info to fix this issue?

**Comment by pjanotti** [comment]
@Krakean is it possible to share the project or solution? I have a small set of test projects and I am not hitting it... it seems that some pattern in the source code is causing this but I don't have such pattern in my test projects. If not possible I will give a try at some random projects, but it is more timing consuming that way. BTW, thanks for the detailed report.

**Comment by Krakean** [comment]
@pjanotti 
No problem. Give me your email please (mine is open, you can see it in my github profile, just in case if you wont share you publically), so I'll send you a link.

**Comment by pjanotti** [comment]
@Krakean I just sent you an e-mail (my e-mail is public too).

**Comment by terrajobst** [comment]
> Using 0.2.15-alpha:

I'm confused by this version number. We only have a `0.1.2-alpha` and `0.1.3-alpha`. Which version are you using?

**Comment by Krakean** [comment]
@pjanotti Sent.

@terrajobst 
Just added to nuget sources this one - https://i.imgur.com/bdXWdKo.png - to get latest binary build.

**Comment by Krakean** [comment]
@pjanotti Heh: https://i.imgur.com/MZEJsij.png
My email was contain .zip archive. It wasn't big, something around ~5mb.
Resend with a link to archive instead of attachment. Check email.

**Comment by Krakean** [comment]
@pjanotti have you received a link to the project?

**Comment by pjanotti** [comment]
@Krakean of course they went straight to junk mail... but now I got them, I may only be able to look at them at the beginning of next week.

**Comment by pjanotti** [comment]
Thanks @Krakean! The issue was very simple: the code was assuming that in certain cases there was always a containing type or method which is not true for pointers - I'll add some unsafe code to my projects with some pointer ops.

**Comment by Krakean** [comment]
@pjanotti 
Thanks. Can you please update Nuget with fixes? :)

**Comment by pjanotti** [comment]
Yeah, sorry about that... it takes a bit of extra effort to get one published because it needs to be signed. I will get the process started, I will let you know when it becomes available.

**Comment by Krakean** [comment]
@terrajobst 
Have you fixed your weird versioning of nightly builds at https://ci.appveyor.com/nuget/platform-compat ?

**Comment by pjanotti** [comment]
@Krakean the nugget 0.2.12-alpha was released earlier today.
